name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - run: |
          pip install -U poetry
          poetry plugin add poetry-version-plugin
      - run: poetry install --without dev
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
