name: Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: lint-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install -U pre-commit

      - name: Lint
        run: pre-commit run --color=always --all-files

  typing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: typing-${{ hashFiles('pyproject.toml') }}

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install package
        run: |
          pip install -U poetry
          poetry install

      - name: Install Pyright
        run: npm install -g --no-package-lock --no-save pyright

      - name: Check types
        run: poetry run pyright

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: test-${{ hashFiles('pyproject.toml') }}

      - name: Install Poetry
        run: pip install -U poetry

      - name: Install package
        run: poetry install

      - name: Install external dependencies
        run: sudo apt-get install -y --no-install-recommends libsndfile-dev portaudio19-dev

      - name: Test
        run: |
          poetry run pytest --color=yes --cov
