name: Test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: pip install -U pre-commit
      - run: cd frontend && npm ci
      - run: pre-commit run --color=always --all-files

  backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: backend-${{ hashFiles('backend/poetry.lock') }}
      - run: pip install -U poetry
      - run: poetry install
      - run: sudo apt-get install -y --no-install-recommends libsndfile-dev portaudio19-dev
      - run: poetry run pyright
      - run: poetry run pytest --color=yes --cov

  frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
